"""Structured conversion service messages."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any


class OutputFormat(str, Enum):
    """Formats generated by the first Spectarr conversion worker."""

    MZML = "mzML"
    MZXML = "mzXML"
    MGF = "mgf"
    MS2 = "ms2"


@dataclass(frozen=True)
class ConversionRequest:
    """A single, allowlisted conversion request."""

    job_id: str
    source_path: str
    recipe: str
    source_name: str | None = None
    recipe_definition: dict[str, Any] | None = None
    parameter_overrides: dict[str, Any] = field(default_factory=dict)
    retain_scratch_on_failure: bool = True

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "ConversionRequest":
        return cls(
            job_id=str(value["job_id"]),
            source_path=str(value["source_path"]),
            source_name=str(value["source_name"]) if value.get("source_name") else None,
            recipe=str(value["recipe"]),
            recipe_definition=value.get("recipe_definition"),
            parameter_overrides=dict(value.get("parameter_overrides") or {}),
            retain_scratch_on_failure=bool(value.get("retain_scratch_on_failure", True)),
        )


@dataclass(frozen=True)
class OutputArtifact:
    """A validated output ready for artifact promotion."""

    path: str
    format: str
    byte_size: int
    sha256: str


@dataclass(frozen=True)
class ConversionResult:
    """Complete result returned to the Spectarr job runner."""

    job_id: str
    status: str
    recipe: str
    image: str
    started_at: str
    finished_at: str
    duration_seconds: float
    converter_version: str | None = None
    command: list[str] = field(default_factory=list)
    arguments: list[str] = field(default_factory=list)
    outputs: list[OutputArtifact] = field(default_factory=list)
    stdout: str = ""
    stderr: str = ""
    error: str | None = None
    scratch_path: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)
