"""user profile and webhook key derivation

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-25 00:21:23.141965
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column(
        'webhook_destinations',
        sa.Column('signing_secret_salt', sa.String(length=64), nullable=False, server_default='rotate-required'),
    )
    op.add_column(
        'webhook_destinations',
        sa.Column('signing_secret_version', sa.Integer(), nullable=False, server_default='1'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_destinations', 'signing_secret_version')
    op.drop_column('webhook_destinations', 'signing_secret_salt')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
