"""webhook delivery leases

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-25 00:26:43.601770
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_deliveries', sa.Column('worker_id', sa.String(length=255), nullable=True))
    op.add_column('webhook_deliveries', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_webhook_deliveries_lease_expires_at'), 'webhook_deliveries', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_worker_id'), 'webhook_deliveries', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_deliveries_worker_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_lease_expires_at'), table_name='webhook_deliveries')
    op.drop_column('webhook_deliveries', 'lease_expires_at')
    op.drop_column('webhook_deliveries', 'worker_id')
    # ### end Alembic commands ###
