import { expect, test } from '@playwright/test'

test('creates and verifies a managed backup with an isolated restore check', async ({ page }, testInfo) => {
  test.skip(process.env.SPECTARR_E2E_BACKUPS !== 'true', 'This installation has no dedicated test backup mount')
  test.setTimeout(120_000)
  await page.goto('/')
  await page.getByLabel('Username').fill(process.env.SPECTARR_E2E_USERNAME ?? 'release-admin')
  await page.getByLabel('Password').fill(process.env.SPECTARR_E2E_PASSWORD ?? 'release-rehearsal-admin-password')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: 'Spectarr overview' })).toBeVisible()
  await page.goto('/settings?section=backups')
  await expect(page.getByRole('heading', { name: 'Backup status' })).toBeVisible()
  await page.getByLabel('Keep newest backups').fill('2')
  await page.getByRole('button', { name: 'Save backup policy' }).click()
  await expect(page.getByRole('button', { name: 'Save backup policy' })).toBeEnabled()
  await page.reload()
  await expect(page.getByLabel('Keep newest backups')).toHaveValue('2')
  await page.getByRole('button', { name: 'Back up now' }).click()
  await expect(page.getByText('Last backup verified', { exact: true })).toBeVisible({ timeout: 90_000 })
  await expect(page.locator('.backup-history tbody tr')).toHaveCount(1)
  await expect(page.locator('.backup-status dl dd').nth(1)).not.toHaveText('None yet')
  await page.screenshot({ path: testInfo.outputPath('backup-settings.png'), fullPage: true })
  await page.getByRole('button', { name: 'Test latest restore' }).click()
  await expect(page.getByRole('button', { name: 'Test latest restore' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Test latest restore' })).toBeEnabled({ timeout: 90_000 })
  await expect(page.getByText('Last backup verified', { exact: true })).toBeVisible()
  await expect(page.getByText('Backup needs attention', { exact: true })).not.toBeVisible()
})
