import { expect, test, type Page } from '@playwright/test'
import { execFileSync } from 'node:child_process'

const content = Buffer.from('BEGIN IONS\nTITLE=extended\nPEPMASS=445.34\nCHARGE=2+\n100 20\n200 30\nEND IONS\n')
test.beforeEach(async ({ page }) => {
  test.skip(process.env.SPECTARR_E2E_GUI !== 'true', 'Requires a disposable GUI test instance without a webhook delivery worker')
  await page.goto('/')
  await page.getByLabel('Username').fill(process.env.SPECTARR_E2E_USERNAME ?? 'release-admin')
  await page.getByLabel('Password').fill(process.env.SPECTARR_E2E_PASSWORD ?? 'release-rehearsal-admin-password')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: 'MassSpec overview' })).toBeVisible()
})
async function headers(page: Page) {
  return { Authorization: `Bearer ${await page.evaluate(() => sessionStorage.getItem('spectarr_access_token'))}` }
}
async function fixture(page: Page) {
  const auth = await headers(page)
  async function create(path: string, data: object) {
    const result = await page.request.post(`/api/v1/${path}`, { headers: auth, data })
    expect(result.ok(), await result.text()).toBeTruthy()
    return result.json()
  }
  const project = await create('projects', { name: `Extended GUI ${crypto.randomUUID().slice(0, 8)}` })
  const experiment = await create('experiments', { project_id: project.id, name: 'Extended experiment' })
  const sample = await create('samples', { experiment_id: experiment.id, name: 'Extended sample' })
  const run = await create('runs', { experiment_id: experiment.id, sample_id: sample.id, name: `extended-run-${project.id.slice(0, 8)}` })
  const response = await page.request.post(`/api/v1/runs/${run.id}/artifacts/upload`, { headers: auth, multipart: { role: 'source', file: { name: 'extended.mgf', mimeType: 'application/octet-stream', buffer: content } } })
  expect(response.ok(), await response.text()).toBeTruthy()
  return { project, experiment, run, source: await response.json(), auth }
}

test('webhook creation, copying, failed updates, retry, toggle, and deletion', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  const name = `GUI webhook ${crypto.randomUUID().slice(0, 8)}`
  await page.goto('/integrations')
  await page.getByRole('button', { name: 'Add webhook' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Name', { exact: true }).fill(name)
  await dialog.getByLabel('HTTPS destination').fill('https://gui-test.invalid/events')
  await dialog.getByRole('button', { name: 'Create webhook' }).click()
  await expect(dialog.getByText('Signing secret', { exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: 'Copy signing secret' }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toMatch(/^whsec_/)
  await dialog.getByRole('button', { name: 'Done' }).click()
  const row = page.locator('.webhook-list > div').filter({ hasText: name })
  const hook = (await (await page.request.get('/api/v1/webhooks', { headers: await headers(page) })).json()).find((item: { name: string }) => item.name === name)
  try {
    await page.route(`**/api/v1/webhooks/${hook.id}`, route => route.fulfill({ status: 503, json: { detail: 'Webhook update unavailable' } }))
    await row.getByRole('button', { name: 'Disable', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('Webhook update unavailable')
    await page.unroute(`**/api/v1/webhooks/${hook.id}`)
    await row.getByRole('button', { name: 'Disable', exact: true }).click()
    await expect(row.getByRole('button', { name: 'Enable', exact: true })).toBeVisible()
    await expect(page.getByRole('alert')).toHaveCount(0)
    await row.getByRole('button', { name: 'Enable', exact: true }).click()
    await expect(row.getByRole('button', { name: 'Disable', exact: true })).toBeVisible()
    await row.getByRole('button', { name: `Delete ${name}` }).click()
    await expect(row).toHaveCount(0)
  } finally {
    await page.unroute(`**/api/v1/webhooks/${hook.id}`)
    await page.request.delete(`/api/v1/webhooks/${hook.id}`, { headers: await headers(page) })
  }
})

test('downloads a validated repository package and verifies its source and checksums', async ({ page }, testInfo) => {
  const { project } = await fixture(page)
  await page.goto(`/projects/${project.id}/metadata`)
  await page.getByRole('button', { name: 'Generate from project' }).click()
  await expect(page.getByLabel('Row 1, source name, column 1', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Validate now' }).click()
  await expect(page.getByRole('status')).toContainText('SDRF validation passed', { timeout: 30_000 })
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download package' }).click()
  const path = testInfo.outputPath('submission.zip')
  await (await download).saveAs(path)
  const output = execFileSync('python3', ['-c', 'import hashlib,sys,zipfile\nwith zipfile.ZipFile(sys.argv[1]) as z:\n names=z.namelist()\n assert "spectarr-submission.json" in names\n assert any(n.endswith(".sdrf.tsv") for n in names)\n checks=z.read("checksums.sha256").decode().splitlines()\n for line in checks:\n  digest,name=line.split(None,1)\n  assert hashlib.sha256(z.read(name.lstrip(" *"))).hexdigest()==digest\n sources=[z.read(n) for n in names if n.startswith("files/") and not n.endswith("/")]\n assert any(b"TITLE=extended" in data for data in sources)\n print("verified")', path], { encoding: 'utf8' })
  expect(output.trim()).toBe('verified')
  await page.getByLabel('Row 1, source name, column 1', { exact: true }).fill('Changed after validation')
  await expect(page.getByRole('button', { name: 'Download package' })).toBeDisabled()
})

test('reclaims a derived file while preserving its source and locks the pending preview', async ({ page }) => {
  const { project, run, source, auth } = await fixture(page)
  const profiles = await (await page.request.get('/api/v1/recipes', { headers: auth })).json()
  const recipe = profiles.find((item: { name: string }) => item.name === 'Standard MGF')
  const response = await page.request.post(`/api/v1/runs/${run.id}/artifacts/upload`, { headers: auth, multipart: { role: 'derived', parent_artifact_id: source.id, recipe_id: recipe.id, file: { name: 'derived.mgf', mimeType: 'application/octet-stream', buffer: Buffer.from(content.toString().replace('extended', 'derived')) } } })
  expect(response.ok(), await response.text()).toBeTruthy()
  const derived = await response.json()
  await expect.poll(async () => {
    const jobs = await (await page.request.get(`/api/v1/jobs?run_id=${run.id}`, { headers: auth })).json()
    return jobs.filter((job: { input_artifact_id: string, state: string }) => job.input_artifact_id === derived.id && ['queued', 'running'].includes(job.state)).length
  }, { timeout: 30_000 }).toBe(0)
  await page.goto('/storage')
  await page.getByRole('button', { name: 'Clear generated files', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('combobox', { name: 'Project', exact: true }).selectOption(project.id)
  let release = () => {}
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/v1/storage/reclaim/preview', async route => { await gate
    await route.continue() })
  await dialog.getByRole('button', { name: 'Calculate reclaimable storage' }).click()
  await expect(dialog.getByRole('combobox', { name: 'Project', exact: true })).toBeDisabled()
  await expect(dialog.getByRole('button', { name: 'Cancel' })).toBeDisabled()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeVisible()
  release()
  await expect(dialog.getByText('1 generated files', { exact: true })).toBeVisible()
  await dialog.getByRole('textbox').fill('wrong')
  await expect(dialog.getByRole('button', { name: 'Clear generated files', exact: true })).toBeDisabled()
  await dialog.getByRole('textbox').fill('PURGE DERIVED FILES')
  await dialog.getByRole('button', { name: 'Clear generated files', exact: true }).click()
  await expect(dialog.getByRole('heading', { name: 'Generated files cleared' })).toBeVisible()
  const original = await page.request.get(`/api/v1/artifacts/${source.id}/download`, { headers: auth })
  expect(await original.body()).toEqual(content)
  expect((await page.request.get(`/api/v1/artifacts/${derived.id}/download`, { headers: auth })).status()).toBe(410)
})

test('retries failed and cancelled batches and refreshes expanded progress', async ({ page }) => {
  const { project, run, auth } = await fixture(page)
  const response = await page.request.post('/api/v1/recipes', { headers: auth, data: { name: `GUI retry ${crypto.randomUUID().slice(0, 8)}`, output_format: 'MS2', parameters: { filters: [] } } })
  expect(response.ok(), await response.text()).toBeTruthy()
  const recipe = await response.json()
  const batchResponse = await page.request.post('/api/v1/processing-batches', { headers: auth, data: { scope_type: 'runs', scope_ids: [run.id], recipe_ids: [recipe.id], mode: 'force' } })
  expect(batchResponse.ok(), await batchResponse.text()).toBeTruthy()
  const batch = await batchResponse.json()
  const jobId = batch.items[0].job_id
  expect((await page.request.patch(`/api/v1/jobs/${jobId}`, { headers: auth, data: { state: 'failed', error: 'GUI controlled failure' } })).ok()).toBeTruthy()
  await page.goto('/processing')
  await page.locator('.batch-main').first().click()
  await expect(page.getByText('GUI controlled failure', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Retry failed', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Cancel queued', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel queued', exact: true }).click()
  await page.getByRole('button', { name: 'Retry cancelled', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Cancel queued', exact: true })).toBeVisible()
  const updated = await (await page.request.get(`/api/v1/processing-batches/${batch.id}`, { headers: auth })).json()
  expect(updated.queued_count).toBe(1)
  await page.getByRole('button', { name: 'Cancel queued', exact: true }).click()
  await page.goto(`/projects/${project.id}/runs`)
  await expect(page.getByRole('link', { name: /extended-run/ }).first()).toBeVisible()
})

test('backup polling preserves unsaved edits through a transient outage', async ({ page }) => {
  await page.goto('/settings?section=backups')
  await page.getByLabel('Keep newest backups').fill('9')
  await page.route('**/api/v1/backups', route => route.fulfill({ status: 503, json: { detail: 'Temporary backup outage' } }))
  await expect(page.getByRole('alert')).toContainText('Temporary backup outage', { timeout: 10_000 })
  await expect(page.getByLabel('Keep newest backups')).toHaveValue('9')
  await expect(page.getByRole('button', { name: 'Back up now' })).toBeDisabled()
  await page.unroute('**/api/v1/backups')
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(page.getByLabel('Keep newest backups')).toHaveValue('9')
})

test('deletes a populated experiment only after an exact confirmation', async ({ page }) => {
  const { project, experiment, run, source, auth } = await fixture(page)
  await page.goto(`/projects/${project.id}/runs`)
  await page.getByRole('button', { name: 'Manage experiments' }).click()
  const dialog = page.getByRole('dialog')
  let release = () => {}
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route(`**/experiments/${experiment.id}/deletion-preview`, async route => { await gate
    await route.continue() })
  await dialog.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Back', exact: true })).toBeDisabled()
  await expect(dialog.getByRole('button', { name: 'Close', exact: true })).toBeDisabled()
  release()
  await expect(dialog.getByText(/permanently removes 1 runs, 1 source files/)).toBeVisible()
  await dialog.getByRole('textbox').fill('Wrong experiment')
  await expect(dialog.getByRole('button', { name: 'Delete experiment' })).toBeDisabled()
  await dialog.getByRole('textbox').fill(experiment.name)
  await dialog.getByRole('button', { name: 'Delete experiment' }).click()
  await expect(dialog.getByRole('alert')).toContainText('Cancel active processing jobs')
  await page.goto('/activity')
  const activity = page.locator('.activity-row').filter({ hasText: run.name })
  await expect(activity.first()).toBeVisible()
  await expect(activity.getByText('Running', { exact: true })).toHaveCount(0, { timeout: 15_000 })
  const cancelButtons = activity.getByRole('button', { name: 'Cancel queued' })
  while (await cancelButtons.count()) {
    const previous = await cancelButtons.count()
    await cancelButtons.first().click()
    await expect.poll(() => cancelButtons.count()).toBeLessThan(previous)
  }
  await page.goto(`/projects/${project.id}/runs`)
  await page.getByRole('button', { name: 'Manage experiments' }).click()
  await dialog.getByRole('button', { name: 'Delete', exact: true }).click()
  await dialog.getByRole('textbox').fill(experiment.name)
  await dialog.getByRole('button', { name: 'Delete experiment' }).click()
  await expect(dialog.getByText('This project has no experiments.')).toBeVisible()
  expect((await page.request.get(`/api/v1/runs/${run.id}`, { headers: auth })).status()).toBe(404)
  expect((await page.request.get(`/api/v1/artifacts/${source.id}/download`, { headers: auth })).status()).toBe(404)
  expect((await page.request.get(`/api/v1/projects/${project.id}`, { headers: auth })).ok()).toBeTruthy()
})

test('search, view switching, missing routes, and expired sessions recover', async ({ page }, testInfo) => {
  const { project, run } = await fixture(page)
  await page.getByLabel('Search all runs').fill('extended-run')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await expect(page).toHaveURL(/q=extended-run/)
  await expect(page.getByRole('link', { name: /extended-run/ }).first()).toBeVisible()
  await page.goto('/projects')
  await page.getByRole('button', { name: 'List view' }).click()
  await expect(page.locator('.project-grid')).toHaveClass(/project-list/)
  await page.getByRole('button', { name: 'Grid view' }).click()
  await expect(page.locator('.project-grid')).not.toHaveClass(/project-list/)
  await page.goto(`/projects/${project.id}/runs/${run.id}/unknown-tab`)
  await expect(page.getByRole('heading', { name: `extended-run-${project.id.slice(0, 8)}` })).toBeVisible()
  await expect(page).toHaveURL(new URL(`/projects/${project.id}/runs/${run.id}`, page.url()).href)
  await page.screenshot({ path: testInfo.outputPath('run-summary.png') })
  await page.goto('/missing-gui-page')
  await page.getByRole('link', { name: 'Back to overview' }).click()
  await expect(page.getByRole('heading', { name: 'MassSpec overview' })).toBeVisible()
  await page.route('**/api/v1/projects?**', route => route.fulfill({ status: 401, json: { detail: 'Expired GUI session' } }))
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Projects', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Sign in' })).toBeVisible()
  expect(await page.evaluate(() => sessionStorage.getItem('spectarr_access_token'))).toBeNull()
})
