import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'

const username = process.env.SPECTARR_E2E_USERNAME ?? 'release-admin'
const password = process.env.SPECTARR_E2E_PASSWORD ?? 'release-rehearsal-admin-password'
const errors = new WeakMap<Page, string[]>()
test.beforeEach(async ({ page }) => {
  test.skip(process.env.SPECTARR_E2E_GUI !== 'true', 'Use a dedicated GUI test instance')
  errors.set(page, [])
  page.on('pageerror', error => errors.get(page)?.push(error.message))
  await page.goto('/')
  await page.getByLabel('Username').fill(username)
  await page.getByLabel('Password').fill(password)
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('heading', { name: 'MassSpec overview' })).toBeVisible()
})
test.afterEach(async ({ page }) => { expect(errors.get(page) ?? []).toEqual([]) })

async function authHeaders(page: Page) {
  return { Authorization: `Bearer ${await page.evaluate(() => sessionStorage.getItem('spectarr_access_token'))}` }
}

async function importFixture(page: Page, project: string) {
  await page.goto('/runs/import')
  await page.getByLabel('Project', { exact: true }).fill(project)
  await page.getByLabel('Experiment', { exact: true }).fill('GUI experiment')
  await page.getByLabel('Source files').setInputFiles({ name: 'gui.mgf', mimeType: 'application/octet-stream',
    buffer: Buffer.from('BEGIN IONS\nTITLE=gui\nPEPMASS=445.34\nCHARGE=2+\n100 20\n200 30\nEND IONS\n') })
  await page.getByRole('button', { name: 'Import 1 run' }).click()
  await expect(page.getByText('1 of 1 imported')).toBeVisible()
  await page.getByRole('link', { name: 'Open gui', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'gui', exact: true })).toBeVisible()
  return page.url().split('/projects/')[1].split('/')[0]
}

test('navigation, keyboard dialogs, mobile menu, and failed-list recovery', async ({ page }) => {
  for (const [url, heading] of [['/projects', 'Projects'], ['/inbox', 'Instrument Inbox'], ['/processing', 'Processing'], ['/storage', 'Storage'], ['/activity', 'Activity'], ['/agents', 'Instrument agents'], ['/automation', 'Automation'], ['/integrations', 'API & MCP'], ['/settings', 'Settings']]) {
    await page.goto(url)
    await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
  }
  await page.goto('/projects')
  const open = page.getByRole('button', { name: 'New project', exact: true })
  await open.click()
  await expect(page.getByLabel('Name', { exact: true })).toBeFocused()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: 'Create project', exact: true }).focus()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Close', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(open).toBeFocused()
  await page.route('**/api/v1/projects?**', route => route.fulfill({ status: 503, json: { detail: 'GUI outage fixture' } }))
  await page.reload()
  await expect(page.getByRole('alert')).toContainText('GUI outage fixture')
  await page.unroute('**/api/v1/projects?**')
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Storage', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Storage', exact: true })).toBeVisible()
  await expect(page.locator('.sidebar')).not.toHaveClass(/sidebar-open/)
})

test('imports, edits and exports current SDRF, downloads source, and browses run tabs', async ({ page }) => {
  test.setTimeout(120_000)
  const projectId = await importFixture(page, `GUI metadata ${crypto.randomUUID().slice(0, 8)}`)
  for (const tab of ['Files', 'Processing', 'Provenance', 'Summary', 'Spectra']) {
    await page.getByRole('navigation', { name: 'Run sections' }).getByRole('link', { name: tab, exact: true }).click()
  }
  const catalogState = page.locator('.spectrum-catalog-state strong')
  await expect(catalogState).toHaveText(/Indexed catalog|Compatibility mode/)
  if (await catalogState.textContent() === 'Compatibility mode') await page.getByRole('button', { name: 'Build catalog', exact: true }).click()
  await expect(catalogState).toHaveText('Indexed catalog', { timeout: 60_000 })
  await expect(page.getByRole('img', { name: 'centroid spectrum' })).toBeVisible()
  const sourceDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download source' }).click()
  expect(await (await sourceDownload).suggestedFilename()).toBe('gui.mgf')
  await page.goto(`/projects/${projectId}/metadata`)
  await page.locator('.project-details > summary').click()
  await page.getByLabel('Keywords, one per line').fill('gui\nreview')
  await page.getByRole('button', { name: 'Save project', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Project metadata saved')
  await page.getByRole('button', { name: 'Generate from project' }).click()
  await page.locator('.sdrf-columns > summary').click()
  await expect(page.getByLabel('Column 1', { exact: true })).toHaveValue('source name')
  await page.getByLabel('Column 1', { exact: true }).press('End')
  await page.getByLabel('Column 1', { exact: true }).pressSequentially(' extra')
  await expect(page.getByLabel('Column 1', { exact: true })).toHaveValue('source name extra')
  await page.getByLabel('Column 1', { exact: true }).fill('source name')
  await page.getByLabel('Row 1, source name, column 1', { exact: true }).fill('GUI edited sample')
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export SDRF', exact: true }).click()
  const path = await (await downloaded).path()
  expect(await readFile(path!, 'utf8')).toContain('GUI edited sample')
  await page.getByLabel('Row 1, source name, column 1', { exact: true }).fill('GUI validated sample')
  await page.getByRole('button', { name: 'Validate now' }).click()
  await expect(page.getByRole('status')).toContainText(/SDRF validation passed|Validation found/, { timeout: 60_000 })
  const saved = await (await page.request.get(`/api/v1/projects/${projectId}/sdrf`, { headers: await authHeaders(page) })).json()
  expect(saved.rows[0].values[0]).toBe('GUI validated sample')
  await page.getByRole('button', { name: 'Add row', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Remove SDRF row 2' })).toBeVisible()
  await page.getByRole('button', { name: 'Remove SDRF row 2' }).click()
  await page.getByRole('button', { name: 'Save table' }).click()
  await expect(page.getByRole('status')).toContainText('Saved SDRF revision')
  page.once('dialog', dialog => dialog.accept('factor value[gui]'))
  await page.getByRole('button', { name: 'Add SDRF column' }).click()
  await page.getByRole('button', { name: /Factors/ }).click()
  await expect(page.getByLabel(/^Row 1, factor value\[gui\], column /)).toBeVisible()
  await page.getByRole('button', { name: /^Remove column \d+, factor value\[gui\]$/ }).click()
  const file = { name: 'gui.sdrf.tsv', mimeType: 'text/tab-separated-values', buffer: await readFile(path!) }
  await page.route('**/sdrf/import', route => route.fulfill({ status: 503, json: { detail: 'SDRF import unavailable' } }))
  await page.locator('input[type=file]').setInputFiles(file)
  await expect(page.getByRole('alert')).toContainText('SDRF import unavailable')
  await page.unroute('**/sdrf/import')
  await page.locator('input[type=file]').setInputFiles(file)
  await expect(page.getByRole('status')).toContainText('Imported 1 SDRF rows')
})

test('metadata-only automation and processing preview errors remain actionable', async ({ page }) => {
  const name = `GUI metadata rule ${crypto.randomUUID().slice(0, 8)}`
  await page.goto('/automation')
  await page.getByRole('button', { name: 'New rule' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Name', { exact: true }).fill(name)
  await dialog.getByRole('checkbox', { name: /Standard mzML/ }).uncheck()
  await expect(dialog.getByRole('checkbox', { name: /Standard mzML/ })).not.toBeChecked()
  await dialog.getByRole('button', { name: 'Create and reconcile' }).click()
  await expect(page.getByRole('button', { name: `Disable ${name}`, exact: true })).toBeVisible()
  await page.getByRole('button', { name: `Disable ${name}`, exact: true }).click()
  await expect(page.getByRole('button', { name: `Enable ${name}`, exact: true })).toBeVisible()
  const profile = `GUI conversion ${crypto.randomUUID().slice(0, 8)}`
  await page.getByRole('button', { name: 'New profile', exact: true }).click()
  await dialog.getByLabel('Name', { exact: true }).fill(profile)
  await dialog.getByLabel('MSCLI named config').selectOption('sage')
  await expect(dialog.getByLabel('Output format')).toBeDisabled()
  await dialog.getByLabel('MSCLI named config').selectOption('')
  await dialog.getByRole('button', { name: 'Save profile' }).click()
  await expect(dialog).toHaveCount(0)
  const projectId = await importFixture(page, `GUI processing ${crypto.randomUUID().slice(0, 8)}`)
  await page.goto(`/projects/${projectId}/runs`)
  await page.getByRole('button', { name: 'Process project' }).click()
  await expect(page.getByRole('dialog').getByText(/to queue/)).toBeVisible()
  await page.getByRole('dialog').getByRole('checkbox', { name: /Standard mzML/ }).uncheck()
  await expect(page.getByRole('dialog').getByText('Select a scope and at least one profile.')).toBeVisible()
  await page.getByRole('dialog').getByRole('checkbox', { name: new RegExp(profile) }).check()
  await expect(page.getByRole('dialog').getByText(/to queue/)).toBeVisible()
  await page.route('**/api/v1/processing-batches/preview', route => route.fulfill({ status: 503, json: { detail: 'Preview unavailable' } }))
  await page.getByLabel('Existing output handling').selectOption('force')
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Preview unavailable')
  await expect(page.getByRole('dialog').getByRole('button', { name: /Queue .* jobs/ })).toBeDisabled()
  await page.unroute('**/api/v1/processing-batches/preview')
  await page.getByLabel('Existing output handling').selectOption('missing')
  await expect(page.getByRole('dialog').getByRole('button', { name: /Queue .* jobs/ })).toBeEnabled()
  await page.getByRole('dialog').getByRole('button', { name: /Queue .* jobs/ }).click()
  await expect(page.getByRole('heading', { name: 'Batch queued' })).toBeVisible()
  await page.getByRole('link', { name: 'Open processing', exact: true }).click()
  await page.locator('.batch-main').first().click()
  await page.getByRole('button', { name: 'Cancel queued' }).click()
  await expect(page.getByRole('button', { name: 'Cancel queued' })).toHaveCount(0)
})

test('settings, users, scoped navigation, credentials, and clipboard errors', async ({ page, browser }) => {
  const suffix = crypto.randomUUID().slice(0, 8)
  await page.goto('/settings?section=downloads')
  await page.getByLabel('Concurrent downloads').selectOption('4')
  await page.getByRole('button', { name: 'Save download settings' }).click()
  await expect(page.getByRole('status')).toContainText('Download settings saved')
  await page.reload()
  await expect(page.getByLabel('Concurrent downloads')).toHaveValue('4')
  await page.getByRole('button', { name: 'Use server default' }).click()
  await expect(page.getByLabel('Concurrent downloads')).toHaveValue('2')
  await page.goto('/settings?section=users')
  await page.getByRole('button', { name: 'Add user' }).click()
  await page.getByLabel('Username', { exact: true }).fill(`viewer-${suffix}`)
  await page.getByLabel('Display name').fill(`GUI Viewer ${suffix}`)
  await page.getByLabel('Password', { exact: true }).fill('gui-viewer-password-for-testing')
  await page.getByRole('button', { name: 'Create user' }).click()
  const row = page.locator('.user-row').filter({ hasText: `GUI Viewer ${suffix}` })
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: 'Disable', exact: true }).click()
  await expect(row.getByRole('button', { name: 'Enable', exact: true })).toBeVisible()
  await row.getByRole('button', { name: 'Enable', exact: true }).click()
  await expect(row.getByRole('button', { name: 'Disable', exact: true })).toBeVisible()
  await page.goto('/settings?section=security')
  await page.getByRole('button', { name: 'Create token' }).click()
  await page.getByRole('dialog').getByLabel('Name', { exact: true }).fill(`GUI token ${suffix}`)
  await page.getByRole('dialog').getByRole('button', { name: 'Create token', exact: true }).click()
  await expect(page.getByText('Token secret', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByRole('button', { name: `Revoke GUI token ${suffix}` }).click()
  await expect(page.getByRole('button', { name: `Revoke GUI token ${suffix}` })).toHaveCount(0)
  await page.goto('/settings?section=unknown')
  await expect(page.getByRole('heading', { name: 'API tokens', exact: true })).toBeVisible()
  const projectId = await importFixture(page, `GUI viewer project ${suffix}`)
  const runUrl = page.url()
  await page.goto('/projects')
  await page.locator('.project-card').filter({ hasText: `GUI viewer project ${suffix}` }).getByRole('button', { name: 'Members' }).click()
  await page.getByRole('dialog').getByRole('combobox', { name: 'User', exact: true }).selectOption({ label: `GUI Viewer ${suffix}` })
  await page.getByRole('dialog').getByRole('button', { name: 'Add member' }).click()
  await expect(page.getByRole('button', { name: `Remove GUI Viewer ${suffix}` })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Close', exact: true }).first().click()
  const context = await browser.newContext()
  const viewer = await context.newPage()
  try {
    await viewer.goto(new URL('/', page.url()).href)
    await viewer.getByLabel('Username').fill(`viewer-${suffix}`)
    await viewer.getByLabel('Password').fill('gui-viewer-password-for-testing')
    await viewer.getByRole('button', { name: 'Sign in' }).click()
    await expect(viewer.getByRole('heading', { name: 'MassSpec overview' })).toBeVisible()
    for (const path of ['/agents', '/automation']) {
      await viewer.goto(new URL(path, page.url()).href)
      await expect(viewer.getByRole('heading', { name: 'MassSpec overview' })).toBeVisible()
    }
    await viewer.goto(new URL('/activity', page.url()).href)
    await expect(viewer.getByRole('heading', { name: 'Activity', exact: true })).toBeVisible()
    await expect(viewer.getByRole('button', { name: 'Cancel queued', exact: true })).toHaveCount(0)
    await viewer.goto(new URL('/settings?section=users', page.url()).href)
    await expect(viewer.getByRole('heading', { name: 'API tokens', exact: true })).toBeVisible()
    await expect(viewer.getByRole('button', { name: 'Add user' })).toHaveCount(0)
    await viewer.goto(new URL('/runs/import', page.url()).href)
    await expect(viewer.getByRole('heading', { name: 'Projects', exact: true })).toBeVisible()
    await viewer.goto(new URL(`/projects/${projectId}/metadata`, page.url()).href)
    await expect(viewer.getByRole('button', { name: 'Save project', exact: true })).toBeDisabled()
    await expect(viewer.getByRole('button', { name: 'Generate from project', exact: true })).toBeDisabled()
    await viewer.goto(runUrl.replace(/\/summary$/, '/processing'))
    await viewer.getByRole('navigation', { name: 'Run sections' }).getByRole('link', { name: 'Processing', exact: true }).click()
    await expect(viewer.getByRole('button', { name: /Generate mzML/ })).toBeDisabled()
    await expect(viewer.getByRole('button', { name: 'Download source' })).toBeEnabled()
    await viewer.goto(new URL('/integrations', page.url()).href)
    await expect(viewer.getByRole('heading', { name: 'API & MCP' })).toBeVisible()
    await expect(viewer.getByRole('alert')).toHaveCount(0)
    await viewer.evaluate(() => { Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: () => Promise.reject(new Error('Clipboard denied')) } }) })
    await viewer.getByRole('button', { name: 'Copy API URL' }).click()
    await expect(viewer.getByRole('alert')).toContainText('Clipboard denied')
    await viewer.goto(new URL('/settings?section=security', page.url()).href)
    await viewer.getByLabel('Current password', { exact: true }).fill('gui-viewer-password-for-testing')
    await viewer.getByLabel('New password', { exact: true }).fill('gui-viewer-updated-password')
    await viewer.getByLabel('Confirm new password', { exact: true }).fill('gui-viewer-mismatch-password')
    await viewer.getByRole('button', { name: 'Change password', exact: true }).click()
    await expect(viewer.getByRole('alert')).toContainText('confirmation does not match')
    await viewer.getByLabel('Confirm new password', { exact: true }).fill('gui-viewer-updated-password')
    await viewer.getByRole('button', { name: 'Change password', exact: true }).click()
    await expect(viewer.getByText('Password changed. Other sessions were revoked.', { exact: true })).toBeVisible()
    const viewerErrors: string[] = []
    viewer.on('pageerror', error => viewerErrors.push(error.message))
    await viewer.route('**/api/v1/auth/logout', route => route.abort())
    await viewer.getByRole('button', { name: 'Sign out' }).click()
    await expect(viewer.getByRole('heading', { name: 'Sign in' })).toBeVisible()
    expect(viewerErrors).toEqual([])
  } finally { await context.close() }
  await page.locator('.project-card').filter({ hasText: `GUI viewer project ${suffix}` }).getByRole('button', { name: 'Members' }).click()
  await page.getByRole('button', { name: `Remove GUI Viewer ${suffix}` }).click()
  await expect(page.getByRole('button', { name: `Remove GUI Viewer ${suffix}` })).toHaveCount(0)
})

test('agent registration, configuration, token rotation, and integration controls', async ({ page, context }) => {
  const name = `GUI agent ${crypto.randomUUID().slice(0, 8)}`
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/agents')
  await page.getByRole('button', { name: 'Register agent', exact: true }).first().click()
  await page.getByRole('dialog').getByLabel('Name', { exact: true }).fill(name)
  await page.getByRole('dialog').getByRole('button', { name: 'Register agent', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('Agent enrollment', { exact: true })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: /Copy/ }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('SPECTARR_AGENT_TOKEN=')
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  page.on('dialog', dialog => dialog.accept())
  const card = page.locator('.agent-card').filter({ hasText: name })
  await card.getByRole('button', { name: 'Disable', exact: true }).click()
  await expect(card.getByRole('button', { name: 'Enable', exact: true })).toBeVisible()
  await card.getByRole('button', { name: 'Enable', exact: true }).click()
  await card.getByRole('button', { name: 'Destination', exact: true }).click()
  await page.getByRole('button', { name: 'Save destination' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await card.getByRole('button', { name: 'Rotate token', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Token rotated', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Copy rotated token' }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).not.toContain('SPECTARR_AGENT_TOKEN=')
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.goto('/integrations')
  await page.getByRole('button', { name: 'Copy API URL' }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('/api/v1')
  expect((await page.request.get('/openapi.json')).ok()).toBeTruthy()
  expect((await page.request.get('/docs')).ok()).toBeTruthy()
})

test('move runs, CSV export, storage preview failures, and experiment deletion', async ({ page }) => {
  const projectId = await importFixture(page, `GUI management ${crypto.randomUUID().slice(0, 8)}`)
  const headers = await authHeaders(page)
  const created = await page.request.post('/api/v1/experiments', { headers, data: { project_id: projectId, name: 'Moved experiment' } })
  expect(created.ok()).toBeTruthy()
  await page.goto(`/projects/${projectId}/runs`)
  const csv = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export CSV' }).click()
  expect(await (await csv).suggestedFilename()).toBe('spectarr-runs.csv')
  await page.getByRole('button', { name: 'Move gui', exact: true }).click()
  await page.getByLabel('Destination project').selectOption(projectId)
  await page.getByLabel('Destination experiment').selectOption({ label: 'Moved experiment' })
  await page.getByRole('button', { name: 'Move runs', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('cell', { name: 'Moved experiment', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Manage experiments' }).click()
  const old = page.getByRole('dialog').locator('.experiment-management-list > div').filter({ hasText: 'GUI experiment' })
  await old.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.getByRole('dialog').getByText(/permanently removes 0 runs/)).toBeVisible()
  await page.getByRole('dialog').getByRole('textbox').fill('GUI experiment')
  await page.getByRole('button', { name: 'Delete experiment', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Delete GUI experiment?' })).toHaveCount(0)
  await page.getByRole('dialog').getByRole('button', { name: 'Close', exact: true }).first().click()
  await page.goto('/storage')
  await page.getByRole('button', { name: 'Clear generated files', exact: true }).click()
  await page.getByRole('dialog').getByRole('combobox', { name: 'Project', exact: true }).selectOption(projectId)
  await page.route('**/api/v1/storage/reclaim/preview', route => route.fulfill({ status: 503, json: { detail: 'Storage preview unavailable' } }))
  await page.getByRole('button', { name: 'Calculate reclaimable storage' }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Storage preview unavailable')
  await page.unroute('**/api/v1/storage/reclaim/preview')
  await page.getByRole('button', { name: 'Calculate reclaimable storage' }).click()
  await expect(page.getByRole('dialog').getByText('0 generated files', { exact: true })).toBeVisible()
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Clear generated files', exact: true })).toBeDisabled()
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel' }).click()
})
